In [2]:
# 1. Environment & Path Setup
import os
import sys

# Add the project root directory to sys.path so 'pipeline' is importable
sys.path.append(os.path.abspath('..'))

import numpy as np  # noqa: F401
import pandas as pd  # noqa: F401
from statsbombpy import sb

from pipeline import (
    get_events_from_timeline,
    get_team_matchids,
    get_teams,
    get_teamseason_matchevents,
)

In [3]:
competitions = sb.competitions()
compeititons_1516 = competitions[competitions["season_name"] == "2015/2016"]

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Premier League 15/16 Season
competition_id = 2
season_id = 27

In [3]:
display(get_teams(2, 27))

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

    home_team_id             home_team
0              1               Arsenal
1             22        Leicester City
2             23               Watford
3             24             Liverpool
4             25           Southampton
5             26          Swansea City
6             27  West Bromwich Albion
7             28       AFC Bournemouth
8             29               Everton
9             30            Stoke City
10            31        Crystal Palace
11            33               Chelsea
12            36       Manchester City
13            37      Newcastle United
14            38     Tottenham Hotspur
15            39     Manchester United
16            40       West Ham United
17            41            Sunderland
18            56          Norwich City
19            59           Aston Villa

Arsenal:
team_id = 1

In [4]:
arsenal_1516_matchids = get_team_matchids(2, 27, 1)

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [5]:
match_df = sb.events(match_id=3754117)
match_df = match_df[match_df['team_id'] == 1]

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [6]:
ars_match_df = get_events_from_timeline(1, 3754117)

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [7]:
display(ars_match_df[['type', 'period', 'timestamp', 'period_offset', 'match_time']])

,type,period,timestamp,period_offset,match_time
0,Starting XI,1,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
1,Half Start,1,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2,Pass,1,0 days 00:00:00.375000,0 days 00:00:00,0 days 00:00:00.375000
3,Ball Receipt*,1,0 days 00:00:02.042000,0 days 00:00:00,0 days 00:00:02.042000
4,Pass,1,0 days 00:00:02.452000,0 days 00:00:00,0 days 00:00:02.452000
...,...,...,...,...,...
1801,Ball Receipt*,2,0 days 00:48:44.771000,0 days 00:46:10.114000,0 days 01:34:54.885000
1802,Pass,2,0 days 00:48:46.230000,0 days 00:46:10.114000,0 days 01:34:56.344000
1803,Ball Receipt*,2,0 days 00:48:47.444000,0 days 00:46:10.114000,0 days 01:34:57.558000
1804,Pass,2,0 days 00:49:13.923000,0 days 00:46:10.114000,0 days 01:35:24.037000
1805,Half End,2,0 days 00:49:16.265000,0 days 00:46:10.114000,0 days 01:35:26.379000

In [9]:
ars_all_match_df = get_teamseason_matchevents(2, 27, 1)

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Found 38 games for the season
Processed match event data for game 1/38
Processed match event data for game 2/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 3/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 4/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 5/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 6/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 7/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 8/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 9/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 10/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 11/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 12/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 13/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 14/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 15/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 16/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 17/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 18/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 19/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 20/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 21/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 22/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 23/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 24/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 25/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 26/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 27/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 28/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 29/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 30/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 31/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 32/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 33/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 34/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 35/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 36/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 37/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 38/38