In [1]:
# 1. Environment & Path Setup
import os
import sys

# Add the project root directory to sys.path so 'pipeline' is importable
sys.path.append(os.path.abspath('..'))

import numpy as np  # noqa: F401
import pandas as pd
from statsbombpy import sb  # noqa: F401

from pipeline import get_team_matchids, get_teamseason_matchevents

In [2]:
arsenal_1516_matchids = get_team_matchids(2, 27, 1)
display(arsenal_1516_matchids)

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

[3754217,
 3754117,
 3754296,
 3753983,
 3754160,
 3754129,
 3754309,
 3754041,
 3754038,
 3753999,
 3754174,
 3754171,
 3754126,
 3754205,
 3754301,
 3754240,
 3754265,
 3754312,
 3754173,
 3753976,
 3753980,
 3753990,
 3754009,
 3754069,
 3754111,
 3754118,
 3754184,
 3754201,
 3754202,
 3754239,
 3754241,
 3754253,
 3754261,
 3754284,
 3754305,
 3754314,
 3754318,
 3754141]

In [3]:
arsenal_1516_events = get_teamseason_matchevents(2, 27, 1)

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Found 38 games for the season
Processed match event data for game 1/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 2/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 3/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 4/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 5/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 6/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 7/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 8/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 9/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 10/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 11/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 12/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 13/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 14/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 15/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 16/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 17/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 18/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 19/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 20/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 21/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 22/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 23/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 24/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 25/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 26/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 27/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 28/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 29/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 30/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 31/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 32/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 33/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 34/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 35/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 36/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 37/38

/home/kishor/Projects/ShotDist/shotdistributionpredictor/.venv/lib/python3.14/site-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Processed match event data for game 38/38

In [4]:
event_types = arsenal_1516_events['type'].unique()

In [5]:
print(event_types)

<StringArray>
[      'Starting XI',        'Half Start',              'Pass',
     'Ball Receipt*',             'Carry',          'Pressure',
     'Dribbled Past',    'Foul Committed',     'Ball Recovery',
           'Dribble',        'Miscontrol',              'Shot',
         'Clearance',              'Duel',            'Shield',
          'Foul Won',       'Goal Keeper',      'Dispossessed',
             'Block',      'Interception',   'Injury Stoppage',
        'Player Off',         'Player On',     'Bad Behaviour',
 'Referee Ball-Drop',    'Tactical Shift',          'Half End',
      'Substitution',  'Own Goal Against',             'Error',
             '50/50',      'Own Goal For',           'Offside']
Length: 33, dtype: str

In [6]:
ipevents = ['Pass', 'Ball Receipt*', 'Carry', 'Dribble', 'Shot', 'Dispossessed', 'Offside', 'Miscontrol']
arsenal_ip_events = arsenal_1516_events[arsenal_1516_events['type'].isin(ipevents)]

In [7]:
unique_players = (
    arsenal_1516_events[["player", "player_id"]]
    .dropna()
    .drop_duplicates()
    .set_index("player_id")["player"]
    .to_dict()
)

In [8]:
len(unique_players)

25

In [9]:
print(unique_players)

{3668.0: 'Theo Walcott', 3496.0: 'Mesut Özil', 11386.0: 'Santiago Cazorla González', 3517.0: 'Aaron Ramsey', 3385.0: 'Alexis Alejandro Sánchez Sánchez', 3498.0: 'Ignacio Monreal Eraso', 3394.0: 'Laurent Koscielny', 3437.0: 'Francis Joseph Coquelin', 6746.0: 'Gabriel Armando de Abreu', 3511.0: 'Héctor Bellerín Moruno', 3461.0: 'Petr Čech', 3713.0: 'Calum Chambers', 3525.0: 'Alex Oxlade-Chamberlain', 3604.0: 'Olivier Giroud', 6631.0: 'Mathieu Flamini', 3475.0: 'Per Mertesacker', 5581.0: 'Joel Nathaniel Campbell Samuels', 3528.0: 'Kieran Gibbs', 3647.0: 'Alex Iwobi', 3388.0: 'Jack Wilshere', 3568.0: 'Mohamed Naser Elsayed Elneny', 42703.0: 'Mikel Arteta Amatriain', 4428.0: 'Mathieu Debuchy', 3569.0: 'Daniel Nii Tackie Mensah Welbeck', 4276.0: 'David Ospina Ramírez'}

In [10]:
unique_player_matches = list(
    arsenal_1516_events[["match_id", "player_id"]]
    .dropna()
    .drop_duplicates()
    .itertuples(index=False, name=None)
)

In [11]:
len(unique_player_matches)

524

In [12]:
pass_events = arsenal_1516_events[arsenal_1516_events['type'] == 'Pass'].dropna(axis = 1, how = 'all')

In [13]:
display(pass_events)

,counterpress,duration,id,index,location,match_id,minute,off_camera,out,pass_aerial_won,...,timestamp,type,under_pressure,period_offset,match_time,teamsheet,mandown,pass_miscommunication,pass_no_touch,pass_straight
2,NaN,0.386674,5f9bdb6d-0379-4f42-9f53-29777f166db5,5,"[61.0, 40.1]",3754217,0,NaN,NaN,NaN,...,0 days 00:00:00.622000,Pass,NaN,0 days 00:00:00,0 days 00:00:00.622000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN,NaN
3,NaN,1.499254,e5d7db8c-d134-4392-a109-9f6efc7f7225,7,"[59.3, 42.1]",3754217,0,NaN,NaN,NaN,...,0 days 00:00:01.008000,Pass,NaN,0 days 00:00:00,0 days 00:00:01.008000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN,NaN
7,NaN,0.986454,fd5039d0-8dd4-417c-9eac-decd2d267e93,10,"[49.5, 41.7]",3754217,0,NaN,NaN,NaN,...,0 days 00:00:05.181000,Pass,NaN,0 days 00:00:00,0 days 00:00:05.181000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN,NaN
10,NaN,0.230623,811b65c7-c0b1-442c-a412-bff5fcf98ff5,14,"[65.9, 48.7]",3754217,0,NaN,NaN,NaN,...,0 days 00:00:07.018000,Pass,True,0 days 00:00:00,0 days 00:00:07.018000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN,NaN
14,NaN,0.138013,f7ab57b3-5714-46d5-b311-52560bb43d8b,28,"[78.8, 32.0]",3754217,0,NaN,NaN,NaN,...,0 days 00:00:14.440000,Pass,NaN,0 days 00:00:00,0 days 00:00:14.440000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,NaN,2.881597,e6e07570-d969-4db1-bb9f-7bc87a3c0f59,3532,"[42.4, 4.5]",3754141,94,NaN,NaN,NaN,...,0 days 00:49:33.267000,Pass,NaN,0 days 00:47:18.635000,0 days 01:36:51.902000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN,NaN
2081,NaN,1.991952,c9ade9cd-c918-4fca-80ef-db9805cfd27f,3535,"[47.2, 33.2]",3754141,94,NaN,NaN,NaN,...,0 days 00:49:37.778000,Pass,NaN,0 days 00:47:18.635000,0 days 01:36:56.413000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN,NaN
2084,NaN,1.860937,c5f827dc-599d-4512-bd19-b1fbbd3bb039,3538,"[78.1, 9.4]",3754141,94,NaN,NaN,NaN,...,0 days 00:49:41.375000,Pass,NaN,0 days 00:47:18.635000,0 days 01:37:00.010000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN,NaN
2087,NaN,1.527055,e7944e64-70b4-467d-a2cb-b85d04dffd89,3541,"[94.2, 5.4]",3754141,94,NaN,NaN,NaN,...,0 days 00:49:43.404000,Pass,NaN,0 days 00:47:18.635000,0 days 01:37:02.039000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN,NaN
2097,NaN,1.125299,9ec2c0be-234f-4ec9-8c60-d35197bdeabf,3557,"[113.8, 57.3]",3754141,94,NaN,NaN,NaN,...,0 days 00:49:55.902000,Pass,NaN,0 days 00:47:18.635000,0 days 01:37:14.537000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN,NaN

In [14]:
carry_events = arsenal_1516_events[arsenal_1516_events['type'].isin(['Carry', 'Dribble'])].dropna(axis = 1, how = 'all')

In [15]:
display(carry_events)

,carry_end_location,dribble_outcome,dribble_overrun,duration,id,index,location,match_id,minute,out,...,team_id,timestamp,type,under_pressure,period_offset,match_time,teamsheet,mandown,dribble_nutmeg,dribble_no_touch
6,"[49.5, 41.7]",NaN,NaN,2.672921,7ec3ada2-d200-4f0b-ab86-f5a464dc4aa7,9,"[43.7, 38.2]",3754217,0,NaN,...,1,0 days 00:00:02.508000,Carry,NaN,0 days 00:00:00,0 days 00:00:02.508000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
8,"[65.9, 48.7]",NaN,NaN,0.851193,d8a6875b-79c2-4f3b-bb08-38cda23763ec,12,"[63.1, 48.9]",3754217,0,NaN,...,1,0 days 00:00:06.167000,Carry,True,0 days 00:00:00,0 days 00:00:06.167000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
23,"[32.3, 13.0]",NaN,NaN,0.724845,fe35c771-9cb1-4de0-88c8-1dcfef32c301,64,"[30.8, 20.7]",3754217,0,NaN,...,1,0 days 00:00:56.174000,Carry,True,0 days 00:00:00,0 days 00:00:56.174000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
27,"[37.0, 26.9]",NaN,NaN,0.897682,eaa749dc-e55d-481a-a84b-bc347e5ac0bf,74,"[35.8, 23.7]",3754217,1,NaN,...,1,0 days 00:01:02.257000,Carry,NaN,0 days 00:00:00,0 days 00:01:02.257000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
30,"[56.3, 19.2]",NaN,NaN,1.344501,b80fbbda-e2d0-4bbf-a317-34d7f7562dc7,77,"[50.9, 26.0]",3754217,1,NaN,...,1,0 days 00:01:03.871000,Carry,NaN,0 days 00:00:00,0 days 00:01:03.871000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091,"[103.2, 56.0]",NaN,NaN,2.318842,cf8e906e-93e4-40f2-83e4-7af039d84d56,3548,"[96.2, 52.8]",3754141,94,NaN,...,1,0 days 00:49:48.760000,Carry,True,0 days 00:47:18.635000,0 days 01:37:07.395000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2093,"[114.5, 68.4]",NaN,NaN,2.999670,1e97b347-d358-4c0a-8cf5-2d1f5d6047e0,3552,"[103.2, 56.0]",3754141,94,NaN,...,1,0 days 00:49:51.079000,Carry,True,0 days 00:47:18.635000,0 days 01:37:09.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2094,NaN,Complete,NaN,0.000000,86a1105d-6709-4745-afa9-83ebee374763,3551,"[103.2, 56.0]",3754141,94,NaN,...,1,0 days 00:49:51.079000,Dribble,True,0 days 00:47:18.635000,0 days 01:37:09.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2095,"[113.8, 57.3]",NaN,NaN,1.823409,6718b084-dfcd-4c45-bf23-1fe4f7ac86f8,3556,"[114.5, 68.4]",3754141,94,NaN,...,1,0 days 00:49:54.079000,Carry,True,0 days 00:47:18.635000,0 days 01:37:12.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2096,NaN,Complete,NaN,0.000000,b6f9a3be-14d9-4c99-864f-486850f4f77d,3555,"[114.5, 68.4]",3754141,94,NaN,...,1,0 days 00:49:54.079000,Dribble,True,0 days 00:47:18.635000,0 days 01:37:12.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN

Clear that carry & dribble events chain. Need to make them all the same event when they do chain

In [16]:
dribble_events = arsenal_1516_events[arsenal_1516_events['type'] == 'Dribble'].dropna(axis = 1, how = 'all')

In [17]:
display(dribble_events)

,dribble_outcome,dribble_overrun,duration,id,index,location,match_id,minute,out,period,...,team_id,timestamp,type,under_pressure,period_offset,match_time,teamsheet,mandown,dribble_nutmeg,dribble_no_touch
41,Incomplete,NaN,0.0,acd7d496-5501-49ea-88f2-038adc7233cd,89,"[116.4, 27.5]",3754217,1,NaN,1,...,1,0 days 00:01:20.871000,Dribble,True,0 days 00:00:00,0 days 00:01:20.871000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
70,Incomplete,True,0.0,0df5ee4d-7383-4751-992e-1e24eb2c5c28,151,"[110.2, 60.3]",3754217,3,True,1,...,1,0 days 00:03:38.094000,Dribble,True,0 days 00:00:00,0 days 00:03:38.094000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
153,Complete,NaN,0.0,e656f736-9d0b-4d38-adbc-da3184d52b82,313,"[61.2, 13.2]",3754217,8,NaN,1,...,1,0 days 00:08:44.631000,Dribble,True,0 days 00:00:00,0 days 00:08:44.631000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
211,Incomplete,NaN,0.0,32d3c417-a3d3-40b9-bbb7-4d99c6e0a59c,392,"[88.2, 23.9]",3754217,10,NaN,1,...,1,0 days 00:10:17.348000,Dribble,True,0 days 00:00:00,0 days 00:10:17.348000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
249,Complete,NaN,0.0,7a88dbcd-6efc-46f9-9b4e-9fd583bddba7,458,"[68.1, 21.1]",3754217,11,NaN,1,...,1,0 days 00:11:55.631000,Dribble,True,0 days 00:00:00,0 days 00:11:55.631000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1796,Complete,NaN,0.0,a3a1886a-f3c3-451b-b32e-11525007c5c0,3077,"[65.9, 7.6]",3754141,81,NaN,2,...,1,0 days 00:36:33.942000,Dribble,True,0 days 00:47:18.635000,0 days 01:23:52.577000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
1951,Complete,NaN,0.0,98e62ef4-bfcb-4a1f-ba32-96917361615f,3328,"[103.6, 76.5]",3754141,88,NaN,2,...,1,0 days 00:43:26.988000,Dribble,True,0 days 00:47:18.635000,0 days 01:30:45.623000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2012,Complete,NaN,0.0,75532b6c-bea1-439b-af15-d678e8b21abb,3447,"[87.4, 3.5]",3754141,91,NaN,2,...,1,0 days 00:46:52.781000,Dribble,True,0 days 00:47:18.635000,0 days 01:34:11.416000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2094,Complete,NaN,0.0,86a1105d-6709-4745-afa9-83ebee374763,3551,"[103.2, 56.0]",3754141,94,NaN,2,...,1,0 days 00:49:51.079000,Dribble,True,0 days 00:47:18.635000,0 days 01:37:09.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN
2096,Complete,NaN,0.0,b6f9a3be-14d9-4c99-864f-486850f4f77d,3555,"[114.5, 68.4]",3754141,94,NaN,2,...,1,0 days 00:49:54.079000,Dribble,True,0 days 00:47:18.635000,0 days 01:37:12.714000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False,NaN,NaN

In [18]:
ballreceipt_events = arsenal_1516_events[arsenal_1516_events['type'].isin(['Ball Receipt*', 'Miscontrol', 'Offside'])].dropna(axis = 1, how = 'all')

In [19]:
display(ballreceipt_events)

,ball_receipt_outcome,duration,id,index,location,match_id,minute,miscontrol_aerial_won,off_camera,out,...,second,team,team_id,timestamp,type,under_pressure,period_offset,match_time,teamsheet,mandown
4,NaN,NaN,a38327b4-a2c6-4282-bb8c-5988520fbd46,6,"[59.1, 42.1]",3754217,0,NaN,NaN,NaN,...,1,Arsenal,1,0 days 00:00:01.008000,Ball Receipt*,NaN,0 days 00:00:00,0 days 00:00:01.008000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False
5,NaN,NaN,38484493-a9cc-4a15-8880-8123bc11de15,8,"[43.7, 38.2]",3754217,0,NaN,NaN,NaN,...,2,Arsenal,1,0 days 00:00:02.508000,Ball Receipt*,NaN,0 days 00:00:00,0 days 00:00:02.508000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False
9,NaN,NaN,470c5b7d-4a36-4abe-8b3e-0573d5d349cb,11,"[63.1, 48.9]",3754217,0,NaN,NaN,NaN,...,6,Arsenal,1,0 days 00:00:06.167000,Ball Receipt*,NaN,0 days 00:00:00,0 days 00:00:06.167000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False
11,Incomplete,NaN,af5be34f-6bf5-4eb0-9b3a-01e18497356a,15,"[71.9, 38.7]",3754217,0,NaN,NaN,NaN,...,7,Arsenal,1,0 days 00:00:07.249000,Ball Receipt*,True,0 days 00:00:00,0 days 00:00:07.249000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False
16,Incomplete,NaN,bd1a223f-4296-4795-80ee-3a196728c61d,32,"[88.0, 43.6]",3754217,0,NaN,NaN,NaN,...,16,Arsenal,1,0 days 00:00:16.285000,Ball Receipt*,NaN,0 days 00:00:00,0 days 00:00:16.285000,"frozenset({(3496, Mesut Özil), (3498, Ignacio ...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2079,NaN,NaN,1338529f-5a07-4f12-bd9b-450c3d653d30,3533,"[44.9, 36.1]",3754141,94,NaN,NaN,NaN,...,36,Arsenal,1,0 days 00:49:36.149000,Ball Receipt*,NaN,0 days 00:47:18.635000,0 days 01:36:54.784000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False
2083,NaN,NaN,4a4060e4-1df9-4483-ad57-63f4b6bda587,3536,"[71.4, 7.6]",3754141,94,NaN,NaN,NaN,...,39,Arsenal,1,0 days 00:49:39.770000,Ball Receipt*,NaN,0 days 00:47:18.635000,0 days 01:36:58.405000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False
2086,NaN,NaN,4470332f-bab9-4bcd-8690-dbd15fbe072c,3539,"[93.0, 4.2]",3754141,94,NaN,NaN,NaN,...,43,Arsenal,1,0 days 00:49:43.236000,Ball Receipt*,NaN,0 days 00:47:18.635000,0 days 01:37:01.871000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False
2088,NaN,NaN,16a93674-4f40-4da4-82d6-963d3f311679,3542,"[108.2, 26.4]",3754141,94,NaN,NaN,NaN,...,44,Arsenal,1,0 days 00:49:44.931000,Ball Receipt*,NaN,0 days 00:47:18.635000,0 days 01:37:03.566000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False
2099,Incomplete,NaN,af801436-5b15-43b2-9c98-7c1c67cf13f7,3558,"[112.4, 36.1]",3754141,94,NaN,NaN,NaN,...,57,Arsenal,1,0 days 00:49:57.027000,Ball Receipt*,NaN,0 days 00:47:18.635000,0 days 01:37:15.662000,"frozenset({(3496, Mesut Özil), (3604, Olivier ...",False

In [20]:
br_duplicates = ballreceipt_events.duplicated(subset = ['match_id', 'match_time'], keep = False)

In [21]:
display(br_duplicates)

4       False
5       False
9       False
11      False
16      False
        ...
2079    False
2083    False
2086    False
2088    False
2099    False
Length: 22109, dtype: bool

miscontrols aren't necessary to consider, add unnecessary noise (say nothing on player intention)

In [22]:
broffside_events = ballreceipt_events[ballreceipt_events['type'].isin(['Ball Receipt*', 'Offside'])]

In [23]:
broffside_duplicates = broffside_events.duplicated(subset = ['match_id', 'match_time'], keep = False)

In [24]:
broffside_duplicates.unique()

array([False])

offside events are not double counted, include

In [26]:
defensive_br_events = arsenal_1516_events[arsenal_1516_events['type'].isin(['Interception', '50/50', 'Ball Recovery', 'Ball Receipt*'])].dropna(axis = 1, how = 'all')

3385.0 - Alexis Sanchez

from mplsoccer import Pitch
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

player_events = arsenal_ip_events[
    arsenal_ip_events["player_id"].eq(3385.0)
].copy()

# Extract StatsBomb x/y coordinates from the location column
player_events[["x", "y"]] = pd.DataFrame(
    player_events["location"].tolist(),
    index=player_events.index
)

player_events = player_events.dropna(subset=["x", "y"])

event_types = sorted(player_events["type"].dropna().unique())

markers = ["o", "s", "^", "D", "P", "X", "v", "<", ">", "*", "h", "p"]
colors = plt.cm.tab20.colors

event_style = {
    event_type: {
        "marker": markers[index % len(markers)],
        "color": colors[index % len(colors)]
    }
    for index, event_type in enumerate(event_types)
}

match_ids = list(arsenal_1516_matchids)
columns = 4
rows = (len(match_ids) + columns - 1) // columns

fig, axes = plt.subplots(
    rows,
    columns,
    figsize=(18, rows * 5),
    squeeze=False
)

pitch = Pitch(
    pitch_type="statsbomb",
    pitch_color="#f7f4ed",
    line_color="#333333",
    linewidth=1
)

for index, match_id in enumerate(match_ids):
    ax = axes.flat[index]
    pitch.draw(ax=ax)

    match_events = player_events[
        player_events["match_id"].eq(match_id)
    ]

    for event_type in event_types:
        events = match_events[
            match_events["type"].eq(event_type)
        ]

        if events.empty:
            continue

        style = event_style[event_type]

        pitch.scatter(
            events["x"],
            events["y"],
            ax=ax,
            marker=style["marker"],
            s=90,
            color=style["color"],
            edgecolors="black",
            linewidth=0.5,
            alpha=0.9
        )

    ax.set_title(f"Match {match_id}", fontsize=10)

# Hide unused subplot axes
for ax in axes.flat[len(match_ids):]:
    ax.remove()

legend_handles = [
    Line2D(
        [0],
        [0],
        marker=event_style[event_type]["marker"],
        color="w",
        label=event_type,
        markerfacecolor=event_style[event_type]["color"],
        markeredgecolor="black",
        markersize=8
    )
    for event_type in event_types
]

fig.legend(
    handles=legend_handles,
    title="Event type",
    loc="center left",
    bbox_to_anchor=(0.91, 0.5)
)

fig.suptitle(
    "Player 3385.0 Events Across Arsenal Matches",
    fontsize=16,
    y=0.995
)

plt.tight_layout(rect=[0, 0, 0.9, 0.98])
plt.show()